"""Step 6.2: every number quoted in the manuscript, as a LaTeX macro in paper/paper_numbers.tex.

    python maps/paper_numbers.py               # write paper/paper_numbers.tex (a few seconds)
    python maps/paper_numbers.py --check       # exit status 1 if the file is out of date
    python maps/paper_numbers.py --recompute   # refresh the slow inputs first (about 2 min)

One macro per number, named \\Num<Topic><Quantity> (letters only, as TeX requires), holding the
number already rounded for the text and without its unit: the text writes
\\qty{\\NumHarrisonSlowModel}{\\second} or \\NumModalFourTransitMin. Percentages are given in per
cent (\\qty{\\NumLongShiftMax}{\\percent}); very small numbers in e-notation for \\num{}.

Where the numbers come from (nothing is typed by hand except the measured values that the
validation scripts already hold as data, which are marked "measured" in the comments):
  * cases.py, paper_tables.py and paper_figures.py (claim 1, case margins, Song head and tail);
  * maps/data/*.npz, the cached data of the paper figures (modal, beta, startup, crawl, validity,
    applications) and maps/data/table_applications.json;
  * validation/harrison_case.py (computed here, about 1 s), validation/data/lodewijks_case.json
    and validation/data/lumped_validation.json (written by their scripts);
  * maps/data/paper_numbers_slow.json: the grip ratios of Lodewijks' 30 s starts (about 30 s to
    compute; refreshed with --recompute).
  * beltloop itself (step 6.3, Section 3): accuracy of the two-pole take-up mass correction and
    the overshoot of a step onset of the resistances (about 6 s);
  * step 6.4 (Section 4, Appendix B): harrison_case.drive_check() (drive without speed control,
    about 9 s), validation/song_case.py, the published Nordell-Ciozda and Muja values, and the
    convergence of the modal tension (about 10 s).
tests/test_paper_numbers.py checks that paper_numbers.tex equals the output of this script and
pins the key numbers against the values of the state document, so a change in the code that
moves a number in the text cannot pass unnoticed.
"""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).parent
ROOT = HERE.parent
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(ROOT / "validation"))

OUT = ROOT / "paper" / "paper_numbers.tex"
SLOW = HERE / "data" / "paper_numbers_slow.json"
LONG = 1000.0          # "conveyors of 1 km or longer" (claim 1)

HEADER = """\
% =====================================================================
% paper_numbers.tex -- GENERATED by maps/paper_numbers.py; do not edit.
% Regenerate with:  python maps/paper_numbers.py   (from the repository root)
% One macro per number quoted in the text, already rounded, without its
% unit. Use them as \\qty{\\NumHarrisonSlowModel}{\\second}, \\num{\\NumX} or
% plain \\NumX. Percentages are in per cent.
% =====================================================================
"""


class Numbers:
    """Ordered collection of (macro, formatted value, comment), grouped by section."""

    def __init__(self):
        self.items: list[tuple[str, str, str]] = []
        self.names: set[str] = set()

    def section(self, title: str):
        self.items.append(("", "", title))

    def add(self, name: str, value, dec: int | str = 2, note: str = ""):
        if not name.isalpha():
            raise ValueError(f"macro name must be letters only: {name}")
        if name in self.names:
            raise ValueError(f"duplicate macro {name}")
        self.names.add(name)
        self.items.append((name, fmt(value, dec), note))

    def tex(self) -> str:
        lines = [HEADER]
        for name, val, note in self.items:
            if not name:
                lines.append(f"\n% ---- {note}")
                continue
            lines.append(f"\\newcommand{{\\Num{name}}}{{{val}}}" + (f"  % {note}" if note else ""))
        return "\n".join(lines) + "\n"


def fmt(v, dec) -> str:
    """Rounded number as text: dec decimals, or 'e1' for one significant figure in e-notation."""
    v = float(v)
    if dec == "e1":
        m, e = f"{v:.0e}".split("e")
        return f"{m}e{int(e)}"
    s = f"{v:.{dec}f}"
    return s.lstrip("-") if float(s) == 0 else s          # no "-0.0"


# ----------------------------------------------------------------------------- inputs
def figure_data(name):
    """Cached data of a paper figure (maps/data/<name>.npz), as paper_figures uses it."""
    import paper_figures as pf
    return pf.cached(name, pf.FIGS[name][0], False)


def slow_inputs(recompute=False) -> dict:
    if SLOW.exists() and not recompute:
        return json.loads(SLOW.read_text())
    import applications as ap
    rows = ap.lodewijks_grip()
    out = dict(lodewijks_grip=[dict(profile=p, zeta1=z, ratio=r, T_t_req=q) for p, z, r, q in rows],
               note="written by maps/paper_numbers.py --recompute; do not edit")
    SLOW.write_text(json.dumps(out, indent=1, sort_keys=True) + "\n")
    return out


def refresh_validation():
    """Rerun the scripts whose summaries are read here (Lodewijks, lumped model)."""
    for script in ("lodewijks_case.py", "fig_lumped_validation.py"):
        subprocess.run([sys.executable, str(ROOT / "validation" / script)], check=True,
                       stdout=subprocess.DEVNULL)


# ----------------------------------------------------------------------------- sections
def claims(N: Numbers):
    """Claim 1: the take-up mass is a small correction for long conveyors; margins per case."""
    import paper_figures as pf
    import paper_tables as pt
    from cases import BY_TAG
    from beltloop import Loop, natural_frequencies, takeup_mass_threshold

    N.section("Claim 1: take-up mass against its threshold (paper_figures.case_margins, case table)")
    rows = pf.case_margins()                      # (tag, L, beta, r, r_lo, shift, shift_lo)
    known = [r for r in rows if r[0] != "WR"]
    long = [r for r in known if r[1] >= LONG]
    N.add("LongBetaMax", max(r[2] for r in long), 3, "largest beta, conveyors of 1 km or longer")
    N.add("LongMarginMin", 1 / max(r[3] for r in long), 1, "smallest beta_5(B1)/beta, alpha = 1")
    N.add("LongMarginMinLow", 1 / max(r[4] for r in long), 1, "the same, lowest coupling")
    N.add("LongShiftMax", max(r[5] for r in long), 1, "largest lengthening of t_1 (%), alpha = 1")
    N.add("LongShiftMaxLow", max(r[6] for r in long), 1, "the same, lowest coupling (%)")
    for tag, L, beta, r, rlo, sh, shlo in known:
        N.add(f"Shift{tag}", sh, 2, f"{tag}: lengthening of t_1 by the take-up mass (%), alpha = 1")
        N.add(f"Shift{tag}Low", shlo, 2, f"{tag}: the same at the lowest coupling (%)")
        N.add(f"BetaRatio{tag}", r, 2, f"{tag}: beta / beta_5(B1)")
    trows = [t for t in pt.case_rows() if t["L"] >= LONG and t["Tt_Wr"] is not None]
    N.add("LongTtWrMin", min(t["Tt_Wr"] for t in trows), 2, "T_t/W_r, conveyors of 1 km or longer")
    N.add("LongTtWrMax", max(t["Tt_Wr"] for t in trows), 2)
    br = [b for t in trows for b in np.atleast_1d(t["beta_ratio"])]     # S: head and tail
    N.add("LongBetaRatioMin", min(br), 2, "beta / beta_5(B1), conveyors of 1 km or longer")
    N.add("LongBetaRatioMax", max(br), 2)

    N.section("Short conveyors where beta starts to matter (WR, Su)")
    wr = [r for r in rows if r[0] == "WR"]
    N.add("WRBeta", wr[0][2], 2, "Wheatley and Rubel, 275 m")
    N.add("WRRatioMin", min(r[3] for r in wr), 2, "beta/beta_5(B1) over the take-up positions")
    N.add("WRRatioMax", max(r[3] for r in wr), 2)
    N.add("WRRatioLowMin", min(r[4] for r in wr), 2, "the same at alpha = 0.8")
    N.add("WRRatioLowMax", max(r[4] for r in wr), 2)
    N.add("WRShiftLowMin", min(r[6] for r in wr), 1, "lengthening of t_1 at alpha = 0.8 (%)")
    N.add("WRShiftLowMax", max(r[6] for r in wr), 1)
    su = BY_TAG["Su"]
    out = []
    for g in (su.gamma(), su.gamma_range()[0]):
        lp = Loop.from_positions(su.sigma_d.value, su.sigma_t[0], g)
        sh = natural_frequencies(lp, 0.0, 1)[0] / natural_frequencies(lp, su.beta, 1)[0] - 1
        out.append((su.beta / takeup_mass_threshold(lp, "B", 1), 100 * sh))
    N.add("SuBeta", su.beta, 2, "Surtees, 805 m, design 2")
    N.add("SuRatio", out[0][0], 2, "beta/beta_5(B1)")
    N.add("SuRatioLow", out[1][0], 2, "the same at alpha = 0.8")
    N.add("SuShift", out[0][1], 1, "lengthening of t_1 (%)")
    N.add("SuShiftLow", out[1][1], 1, "the same at alpha = 0.8 (%)")


def modal(N: Numbers):
    """Claim 2 and fig_modal: frequencies and participation by strand; intermediate drive."""
    from cases import BY_TAG
    from beltloop import Loop, natural_frequencies
    d = figure_data("modal")
    N.section("Frequencies and participation (fig_modal; head drive, beta -> 0)")
    N.add("ModalTauMin", d["T1"].min(), 2, "tau_1 = t_1 c_r / L over the map")
    N.add("ModalTauMax", d["T1"].max(), 2)
    N.add("ModalFourTransitMin", d["ratio"].min(), 3, "tau_1 / (4 tau_B), lower bound over the map")
    N.add("ModalFourTransitOver", 100 * (1 / d["ratio"].min() - 1), 0,
          "largest overestimate of the four-transit rule (%)")
    N.add("ModalParticipationMin", d["F1"].min(), 2, "effective-mass fraction of the fundamental")
    N.add("ModalParticipationMax", d["F1"].max(), 2)
    N.add("ModalHatched", 100 * np.mean(np.abs(d["dF1"]) > 0.05), 0,
          "share of the (xi, gamma) plane where beta = 0.1 changes it by > 5 % (%)")
    for g, name in ((1.0, "One"), (2.0, "Two")):
        T = [2 * np.pi / natural_frequencies(Loop.from_positions(0.0, x, g), 0.0, 1)[0]
             for x in (1e-6, 1 - 1e-6)]
        N.add(f"HeadTailRatioGamma{name}", T[0] / T[1], 2,
              f"t_1 with the take-up at the head over t_1 at the tail, gamma = {g:g}")
    rmax = max(r.max() for r in d["ratio_l1"])
    N.add("IntermediateRatioMax", rmax, 2, "tau_1/(4 tau_B) with an intermediate drive, gamma <= 3")
    N.add("IntermediateOverMax", 100 * (rmax - 1), 0, "the same as an excess over four transits (%)")
    nc = d["nc"]                                   # sigma_d, ratio, T1, T1 with a head drive
    N.add("NCRatio", nc[1], 2, "Nordell and Ciozda: tau_1/(4 tau_B)")
    N.add("NCPeriod", nc[2], 1, "Nordell and Ciozda: t_1 (s), beta -> 0")
    N.add("NCPeriodHead", nc[3], 1, "the same strands with a head drive (s)")
    N.add("NCIncrease", 100 * (nc[2] / nc[3] - 1), 0, "(%)")
    su = d["sasol"]
    N.add("SuFourTransit", su[1], 3, "Surtees: tau_1/(4 tau_B), beta -> 0")
    N.add("SuFourTransitLow", su[2], 3, "the same at alpha = 0.8")

    N.section("Song et al. (2012): take-up next to the head drive against the tail")
    s = BY_TAG["S"]
    for beta, suffix, note in ((s.beta, "", "beta from the take-up tension (case table)"),
                               (0.0, "Light", "beta -> 0, as Song et al. modelled it; quoted in the text (step 6.2)")):
        T = [2 * np.pi * s.L.value / (s.c_r * natural_frequencies(
            Loop.from_positions(0.0, x, s.gamma()), beta, 1)[0]) for x in s.xis]
        N.add(f"SongPeriodHead{suffix}", T[0], 1, f"t_1 (s), {note}")
        N.add(f"SongPeriodTail{suffix}", T[1], 1)


def beta_regime(N: Numbers):
    d = figure_data("beta")
    N.section("Take-up mass threshold (fig_beta)")
    B1 = d["B1"][np.isfinite(d["B1"])]
    N.add("BetaFiveBOneMin", B1.min(), 2, "beta_5 of the fundamental (B1) over the map")
    N.add("BetaFiveBOneMax", B1.max(), 2)
    N.add("BetaFiveBOneMedian", np.median(B1), 2)
    B2 = d["B2"][np.isfinite(d["B2"])]
    N.add("BetaFiveBTwoMedian", np.median(B2), 2)
    sel = d["gams"] >= 1.4 - 1e-9
    Z = d["B1"][sel]
    N.add("BetaFiveMinGammaOneFour", Z[np.isfinite(Z)].min(), 2,
          "smallest beta_5(B1) for gamma >= 1.4, any take-up position (at the tail)")
    near = Z[:, d["xis"] <= 0.1]
    N.add("BetaFiveMinNearDrive", near[np.isfinite(near)].min(), 2,
          "smallest beta_5(B1), gamma >= 1.4, xi <= 0.1: the rule T_t <~ W_r/4 (n = 2) is "
          "stated for a take-up near the drive (decision of step 6.2)")
    Zf = np.where(np.isfinite(d["B1"]), d["B1"], np.inf).min(axis=1)
    N.add("RuleGammaAnyPosition", d["gams"][np.argmax(Zf >= 0.5)], 1,
          "gamma above which beta_5(B1) >= 0.5 for every take-up position (grid 0.025)")
    tol = 0.05
    N.add("SinglePoleCoefficient", 4 * ((1 + tol) ** 2 - 1), 2, "beta_5 ~ 0.41 m~ (one pole)")
    N.add("BetaFiveAOneSlope", 2 * ((1 + tol) ** 2 - 1), 3, "beta_5(A1) ~ 0.205 xi (uniform strand)")


def startup(N: Numbers):
    from beltloop import PEAK_FACTOR
    import paper_figures as pf
    d = figure_data("startup")
    R = d["R"]
    N.section("Universal start-up curve (fig_startup; sine profile unless stated)")
    D = d["D_sine"]
    i = int(np.argmax(D))
    N.add("StartPeakMax", D[i], 3, "largest amplification D")
    N.add("StartPeakAt", R[i], 2, "at tau_a / tau_s")
    for r, name in ((1, "One"), (2, "Two"), (5, "Five"), (10, "Ten")):
        N.add(f"StartD{name}", np.interp(r, R, D), 3, f"D at tau_a / tau_s = {r}")
    N.add("StartTriangularMax", d["D_triangular"].max(), 3)
    N.add("StartParabolicMax", d["D_parabolic"].max(), 3)
    m = {k: np.interp(5.0, R, d[f"D_{k}"] * PEAK_FACTOR[k]) for k in ("sine", "triangular")}
    N.add("StartTriangularExcess", 100 * (m["triangular"] / m["sine"] - 1), 0,
          "triangular over sine per unit mean acceleration, tau_a = 5 tau_s (%)")
    for z, name in ((0.02, "Two"), (0.05, "Five"), (0.1, "Ten")):
        N.add(f"StartDamp{name}", d[f"D_z{z:g}"].max(), 3, f"largest D with zeta_1 = {z:g}")
    N.add("StartTravelMax", d["Dfree_sine"].max(), 2, "take-up travel over quasi-static, largest")
    for r, name in ((1, "One"), (2, "Two"), (5, "Five")):
        N.add(f"StartRes{name}", np.interp(r, R, d["D_res"]), 3,
              f"resistances with phi = V/V_inf, tau_a / tau_s = {r}")
    rc = d["rc"]
    for r0, name in ((0.8, "Eight"), (0.5, "Five")):
        ok = rc >= r0 - 1e-9
        N.add(f"CollapseEntry{name}", 100 * d["dev_in"][:, ok].max(), 1,
              f"loop against the strand curve at the drive entry, tau_a >= {r0:g} tau_1 (%)")
        N.add(f"CollapseExit{name}", 100 * d["dev_out"][ok].max(), 1, "the same at the exit (%)")
    N.add("CollapseFastMax", 100 * d["dev_in"][:, 0].max(), 0,
          f"entry, fastest start (tau_a = {rc[0]:.1f} tau_1), gamma != 1 (%)")
    for tag, r in pf.PRACTICE:
        N.add(f"Practice{tag}", r, 2, f"{tag}: published start time over its t_1")


def crawl(N: Numbers):
    d = figure_data("crawl")
    N.section("Initial crawl (fig_crawl; rho = 1, 5 and zeta_1 = 0.01, 0.1)")
    combos = [(r, z) for r in (1, 5) for z in (0.01, 0.1)]
    ramp = [d[f"ramp_{r:g}_{z:g}"] for r, z in combos]
    at = lambda arr, x, col: np.interp(x, d["trs"], arr[:, col])
    N.add("CrawlAbruptMin", min(a[0, 0] for a in ramp), 2, "entry peak / (R + m a_m), abrupt onset")
    N.add("CrawlAbruptMax", max(a[0, 0] for a in ramp), 2)
    N.add("CrawlRampHalfMin", min(at(a, 0.5, 0) for a in ramp), 2, "ramp of 0.5 tau_1")
    N.add("CrawlRampHalfMax", max(at(a, 0.5, 0) for a in ramp), 2)
    N.add("CrawlRampOneMin", min(at(a, 1.0, 0) for a in ramp), 2, "ramp of one tau_1")
    N.add("CrawlRampOneMax", max(at(a, 1.0, 0) for a in ramp), 2)
    N.add("CrawlTravelAbruptMin", min(a[0, 1] for a in ramp), 1, "take-up travel / quasi-static")
    N.add("CrawlTravelAbruptMax", max(a[0, 1] for a in ramp), 1)
    N.add("CrawlTravelRampOneMax", max(at(a, 1.0, 1) for a in ramp), 2)


def validity(N: Numbers):
    d = figure_data("validity")
    N.section("Validity conditions (fig_validity; gamma = 2, rho = 1 in (c) and (d))")
    N.add("ReboundMax", np.max(-d["cmin_0"]), 2, "rebound of strand B, no resistances, / (m_B a_m)")
    q = np.vstack([d["req_1"], d["req_3"]])        # tau_a = tau_1 and 3 tau_1
    N.add("ValidityExitMax", q[:, 0].max(), 2, "required T_2 at the exit / (m_belt a_m)")
    N.add("ValidityGripThreeMin", q[:, 2].min(), 2, "grip with e^{mu theta} = 3")
    N.add("ValidityGripThreeMax", q[:, 2].max(), 2)
    N.add("ValidityGripSixteenMin", q[:, 3].min(), 2, "grip with e^{mu theta} = 16")
    N.add("ValidityGripSixteenMax", q[:, 3].max(), 2)
    left = d["sts"] < 0.5
    T = d["tight"][:, 0]
    N.add("TightMin", T[left].min(), 2, "take-up tension on the tight side / (m_belt a_m)")
    N.add("TightMax", T[left].max(), 2)
    N.add("SlackMin", T[~left].min(), 2, "the same on the slack side")
    N.add("SlackMax", T[~left].max(), 2)


def applications(N: Numbers, slow: dict):
    import applications as ap
    import beta_min as bm
    from cases import BY_TAG
    rows = json.loads((HERE / "data" / "table_applications.json").read_text())
    by = {(r["tag"], r["label"]): r for r in rows}
    N.section("Application to field conveyors (fig_applications, table_applications)")
    lo, lot, lomin = by["Lo", "real"], by["Lo", "tail"], by["Lo", "real, shortest start"]
    N.add("LoTt", lo["T_t"] / 1e3, 1, "Lodewijks: take-up tension of the case (kN)")
    N.add("LoTtReq", lo["req"] / 1e3, 1, "required for the 30 s start, real position (kN)")
    N.add("LoTtReqTail", lot["req"] / 1e3, 1, "the same, take-up at the tail (kN)")
    N.add("LoShortest", lo["t_a_req"], 0, "shortest admissible sine start, real position (s)")
    N.add("LoShortestOverPeriod", lomin["t_a"] / lomin["T1"], 1, "the same over t_1")
    N.add("LoPeriodChange", 100 * (1 - lot["T1"] / lo["T1"]), 0, "t_1, real to tail (%)")
    c = BY_TAG["Lo"]
    r_r, _, _ = bm.strand_resistances(c)
    N.add("LoXiLimit", (c.takeup().T_t - c.F_U.value / (c.E.value - 1)) / (r_r * c.L.value), 2,
          "beyond this take-up position no start is admissible (running grip fails)")
    grip = slow["lodewijks_grip"]
    rat = [g["ratio"] for g in grip]
    N.add("LoGripRatioMin", min(rat), 1, "max T_entry/T_exit in the 30 s starts of Table 8.7")
    N.add("LoGripRatioMax", max(rat), 1)
    N.add("LoGripFactor", c.E.value, 1, "e^{mu theta} of his drive")
    sine = [g for g in grip if g["profile"].startswith("Harrison") and g["zeta1"] == 0.0][0]
    N.add("LoSineTtFactor", sine["T_t_req"] / lo["T_t"], 1,
          "sine 30 s start: T_t needed for grip over his T_t")
    sm, smt = by["SM", "real"], by["SM", "tail"]
    N.add("SMTtReq", sm["req"] / 1e3, 0, "Suchorab-Matuszewska: required T_t, real position (kN)")
    N.add("SMTtReqTail", smt["req"] / 1e3, 0, "the same at the tail (kN)")
    N.add("SMTt", sm["T_t"] / 1e3, 0, "take-up tension of the case (kN)")
    N.add("SMShortest", sm["t_a_req"], 0, "shortest admissible start (s)")
    N.add("SMPeriodChange", 100 * (1 - smt["T1"] / sm["T1"]), 0, "t_1, real to tail (%)")
    N.add("SMReferenceStart", sm["t_a"], 1, "reference start 3 t_1 (s)")
    su, sut = by["Su", "real"], by["Su", "tight side"]
    N.add("SuTtReq", su["req"] / 1e3, 1, "Surtees: required T_t after the drive (kN)")
    N.add("SuTtReqTight", sut["req"] / 1e3, 0, "the same on the tight side (kN)")
    N.add("SuTightFactor", sut["req"] / su["req"], 0, "tight over slack side")
    N.add("SuShortest", su["t_a_req"], 1, "shortest admissible start (s)")
    N.add("SuExitTight", sut["exit_min"] / 1e3, 0, "lowest exit tension on the tight side (kN)")


def validation(N: Numbers):
    import harrison_case as hc
    from cases import NORDELL_CIOZDA as nc
    N.section("Validation: Harrison (1983, 1985b) (validation/harrison_case.py)")
    h = hc.summary()
    N.add("HarrisonSlowMeas", h["slow_meas"], 1, "measured slow period (s), our read-out of Fig. 5e")
    N.add("HarrisonSlowModel", h["slow"], 1, "model (s): n = 4, gamma = 0.97, xi = 0.005")
    N.add("HarrisonSlowExcess", 100 * (h["slow"] / h["slow_meas"] - 1), 0, "(%)")
    N.add("HarrisonSlowModelMin", h["slow_band"][0], 1, "model over the measured gamma band (s)")
    N.add("HarrisonSlowModelMax", h["slow_band"][1], 1)
    N.add("HarrisonSecondMin", h["second"][0], 1, "second period of the model (s)")
    N.add("HarrisonSecondMax", h["second"][1], 1)
    N.add("HarrisonWaveMeas", h["wave_meas"], 1, "measured ripple (s), Fig. 5c")
    N.add("HarrisonEmbeddedMax", h["embedded_max"], 1,
          "embedded-mass model, largest fundamental for xi <= 0.2 (s)")
    N.add("HarrisonBetaMin", h["beta"][0], 3, "beta = 4M/(n^2 mu_r L), n = 4, rho = 79 and 39 kg/m")
    N.add("HarrisonBetaMax", h["beta"][1], 3)
    N.add("HarrisonGammaMeas", h["gamma_meas"], 2, "gamma measured on the empty belt (1985b)")
    N.add("HarrisonGammaMeasMin", h["gamma_band"][0], 2)
    N.add("HarrisonGammaMeasMax", h["gamma_band"][1], 2)
    N.add("HarrisonStillMeas", h["still_meas"], 1, "return belt still after the start (s), measured")
    N.add("HarrisonTransit", h["t_back"], 1, "model: time until the wave returns (s)")
    N.add("HarrisonStillSpeed", h["v_still"], 3, "model: largest belt speed there meanwhile (m/s)")
    N.add("HarrisonCarriageModel", h["carriage_7s"], 1, "model: carriage travel at 7 s (m)")
    N.add("HarrisonCarriageMeas", h["carriage_meas"], 0, "measured carriage travel, about (m)")
    N.add("HarrisonStoredMax", h["stored_max"], 0, "model: belt stored in the loop (m)")
    N.add("HarrisonStoredMeas", 24, 0, "belt released by the loop at start-up, 1985b text (m)")
    N.add("HarrisonTransmissionMin", h["transmission_7s"][0], 2, "|t| through the take-up at 7 s")
    N.add("HarrisonTransmissionMax", h["transmission_7s"][1], 2)

    N.section("Validation: Harrison, drive without speed control (Section 3.6; step 6.4)")
    # base model n = 4, gamma = 0.97, rho = 79 kg/m; harrison_case.drive_check()
    N.add("HarrisonFreeDriveSlow", h["drive_free_slow"], 1, "free drive (m_d -> 0): slow period (s)")
    N.add("HarrisonFreeDriveSecond", h["drive_free_second"], 1, "free drive: second period (s), the loop transit")
    N.add("HarrisonDriveMassMeas", h["drive_md_meas"], 1, "m_d that alone gives the measured slow period")
    N.add("HarrisonDriveMassBeltRatio", h["drive_md_meas_belt_ratio"], 1,
          "that reduced drive mass over the mass of the whole belt")
    N.add("HarrisonDriveMassSecond", h["drive_md_meas_second"], 1, "second period with that m_d (s)")
    N.add("HarrisonRunForce", h["drive_run_force"] / 1e3, 0, "running force 900 kW / 3.7 m/s (kN)")
    N.add("HarrisonSlipNatural", 100 * hc.SLIP_NATURAL, 0, "assumed slip, natural characteristic (%)")
    N.add("HarrisonSlipSoftMin", 100 * min(hc.SLIP_SOFT), 0, "assumed slip, rotor resistance in circuit (%)")
    N.add("HarrisonSlipSoftMax", 100 * max(hc.SLIP_SOFT), 0)
    N.add("HarrisonDashpotNatural", h["drive_c_natural"], 0, "c_hat on the natural characteristic")
    N.add("HarrisonDashpotNaturalChange", 100 * h["drive_natural_change"], 1,
          "largest change of the slow period with it, m_d = 0.1-3 (%)")
    N.add("HarrisonDashpotSoftMin", h["drive_c_soft"][0], 1, "c_hat with rotor resistance in circuit")
    N.add("HarrisonDashpotSoftMax", h["drive_c_soft"][1], 1)
    N.add("HarrisonSoftSlowMin", h["drive_soft_slow"][0], 1, "slow period with it, m_d = 1-3 (s)")
    N.add("HarrisonSoftSlowMax", h["drive_soft_slow"][1], 1)
    N.add("HarrisonSoftZetaMin", h["drive_soft_zeta"][0], 2, "its damping ratio")
    N.add("HarrisonSoftZetaMax", h["drive_soft_zeta"][1], 2)
    N.add("HarrisonSoftSecondMin", h["drive_soft_second"][0], 1, "second period with it (s)")
    N.add("HarrisonSoftSecondMax", h["drive_soft_second"][1], 1)
    N.add("HarrisonDriveMassMin", min(hc.DRIVE_MASSES), 1, "range of m_d tried")
    N.add("HarrisonDriveMassMax", max(hc.DRIVE_MASSES), 0)

    N.section("Validation: Nordell and Ciozda (1984), arrival times (case geometry, two wave speeds)")
    L, cr = nc["L"], nc["c_r"]
    cc = cr / nc["gamma"]
    xd = nc["sigma_d"] * L
    tB = xd / cr + xd / cc
    tC = xd / cr + L / cc + (1 - nc["sigma_t"]) * L / cr
    N.add("NCArrivalB", tB, 2, "wave from the drive to point B (s); measured 3.72")
    N.add("NCArrivalC", tC, 2, "wave from the drive to the take-up, point C (s); measured 5.86")
    N.add("NCArrivalBMeas", 3.72, 2, "measured (their Fig. 10)")
    N.add("NCArrivalCMeas", 5.86, 2, "measured (their Fig. 11)")
    N.add("NCSpeedReturn", nc["c_r"], 0, "their wave speed on the empty return strand (m/s)")
    N.add("NCSpeedCarry", cr / nc["gamma"], 0, "their wave speed on the loaded carry strand (m/s)")

    N.section("Validation: Muja P2 (cdi1998), published values")
    muja = dict(L=6.1, t=3.1, c_meas=1968.0, c_calc=1985.0)   # 6.1 km, 3.1 s; E = 5154 N/mm^2, 1307 kg/m^3
    N.add("MujaLength", muja["L"], 1, "km")
    N.add("MujaTime", muja["t"], 1, "wave travel time in an emergency stop, empty belt (s)")
    N.add("MujaSpeedMeas", muja["c_meas"], 0, "(m/s)")
    N.add("MujaSpeedCalc", muja["c_calc"], 0, "from E and density (m/s)")
    N.add("MujaSpeedDiff", 100 * (1 - muja["c_meas"] / muja["c_calc"]), 1, "(%)")

    N.section("Cross-comparison: Song et al. (2012) (validation/song_case.py)")
    import song_case as sc
    so = sc.summary()
    N.add("SongCcModel", so["c_c"], 1, "carry wave speed from their data (m/s)")
    N.add("SongCcPub", so["pub"]["c_c"], 1, "published")
    N.add("SongCrModel", so["c_r"], 1, "return wave speed from their data (m/s)")
    N.add("SongCrPub", so["pub"]["c_r"], 1, "published")
    N.add("SongFRunModel", so["F_run"] / 1e3, 0, "running drive force from their resistance law (kN)")
    N.add("SongFRunPub", so["pub"]["F_run"] / 1e3, 1, "published (kN)")
    N.add("SongFRunDiff", 100 * abs(so["F_run"] / so["pub"]["F_run"] - 1), 0, "(%)")
    N.add("SongTtPub", so["pub"]["T_t"] / 1e3, 0, "published tension at the tail take-up (kN)")
    N.add("SongTtMass", so["takeup_mass_tension"] / 1e3, 0, "what 4500 kg hold on two strands (kN)")
    N.add("SongTravelPub", so["pub"]["travel"], 2, "published steady take-up travel (m)")
    N.add("SongTravelTensions", so["travel_from_their_tensions"], 1,
          "take-up travel implied by their own running tensions (m)")

    N.section("Cross-comparison: Lodewijks (1996) ch. 8 (validation/data/lodewijks_case.json)")
    lc = json.loads((ROOT / "validation" / "data" / "lodewijks_case.json").read_text())
    N.add("LodewijksPeakDevMin", 100 * lc["peak_dev_min"], 0, "peak strain, model / his - 1 (%)")
    N.add("LodewijksPeakDevMax", 100 * lc["peak_dev_max"], 0)
    N.add("LodewijksPeriodMeas", lc["period_lodewijks_strain"], 1, "his oscillation period (s)")
    N.add("LodewijksPeriodModel", lc["period_model"], 1, "ours (s)")
    pk = lc["peak_eps"]
    N.add("LodewijksLinearGap", 100 * abs(pk["linear offset"]["model"] / pk["linear"]["model"] - 1), 0,
          "model: offset vs plain linear ramp, peak strain difference (%)")
    N.add("LodewijksLinearGapHis", 100 * abs(pk["linear offset"]["lodewijks"] / pk["linear"]["lodewijks"] - 1),
          0, "the same in his Table 8.7 (%)")
    N.add("LodewijksTravelMeanHis", lc["travel_mean_lodewijks"], 1,
          "mean take-up travel after his 30 s start (m), our fit of his Fig. 8.42")
    N.add("LodewijksTravelSweepHis", lc["travel_sweep_50_lodewijks"], 1,
          "his largest take-up travel for a 50 s start (m), Fig. 8.46")
    N.add("LodewijksTravelMeanModel", lc["travel_mean_model"], 1, "ours after the 30 s start (m)")
    N.add("LodewijksPeriodEmpty", lc["period_empty_carry"], 1, "ours with an empty carry strand (s)")
    N.add("LodewijksPeriodOwnDrive", lc["period_torque_own_drive"], 1,
          "ours, torque-imposed drive with his drive inertia (s)")
    N.add("LodewijksOwnDriveMass", lc["md_own_drive"], 2, "m_d of his motor, gearbox and pulley")

    N.section("Verification: lumped-mass model (validation/data/lumped_validation.json)")
    lv = json.loads((ROOT / "validation" / "data" / "lumped_validation.json").read_text())
    cases = [lv[k] for k in ("A", "B")]
    N.add("LumpedTensionErr", max(c["tension_err"] for c in cases), "e1",
          "dynamic tension, N = 1000, largest relative difference")
    N.add("LumpedTravelErr", max(c["travel_err"] for c in cases), "e1", "take-up travel, N = 1000")
    N.add("LumpedFreqErr", max(c["freq_err"][-1] for c in cases), "e1", "first five frequencies")
    N.add("LumpedOrder", min(min(c["freq_order"], c["field_order"]) for c in cases), 1,
          "observed order of convergence")
    N.add("LumpedElements", cases[0]["N"][-1], 0, "elements of the finest lumped model")


def solution(N: Numbers):
    """Step 6.3, Section 3 (closed-form solution): accuracy of the take-up mass correction and
    the overshoot of a step onset of the resistances (about 6 s)."""
    from beltloop import (Loop, StartProfile, modal_basis, natural_frequencies, startup_response,
                          takeup_mass_approx)
    N.section("Closed-form solution (Section 3): two-pole mass correction against exact roots")
    # head drive, 1 <= gamma <= 3, take-up anywhere on the return strand
    worst, worst1 = 0.0, 0.0
    for g in np.linspace(1.0, 3.0, 21):
        for xi in np.linspace(0.01, 0.99, 99):
            lp = Loop.from_positions(0.0, xi, g)
            ex = natural_frequencies(lp, 0.1, 3)
            worst = max(worst, np.max(np.abs(takeup_mass_approx(lp, 0.1, 3) / ex - 1)))
            ex1 = natural_frequencies(lp, 1.0, 1)[0]
            worst1 = max(worst1, abs(takeup_mass_approx(lp, 1.0, 1)[0] / ex1 - 1))
    N.add("MassCorrErrTenth", 100 * worst, 1,
          "largest error of the two-pole frequencies, beta = 0.1, modes 1-3 (%)")
    N.add("MassCorrErrFundOne", 100 * worst1, 1, "the same for the fundamental at beta = 1 (%)")

    N.section("Closed-form solution (Section 3): step onset of the resistances")
    # tests/test_response.py::test_step_overshoot_can_exceed_two (confirmed with FE in phase 3)
    lp = Loop.from_positions(0.0, 0.05, 2.0, r_return=1.0, r_carry=1.0)
    mb = modal_basis(lp, 0.1, 300)
    tau = np.linspace(0.0, 60.0, 6001)
    step = startup_response(mb, StartProfile("sine", 5.0, "step"), 0.0, tau).tension([2.0])
    none = startup_response(mb, StartProfile("sine", 5.0, "none"), 0.0, tau).tension([2.0])
    N.add("StepOvershootEntry", np.max(np.abs(step - none)) / abs(lp.quasi_static("r", [2.0])[0]), 1,
          "peak / quasi-static resistance tension at the drive entry, gamma = 2, beta = 0.1, "
          "xi = 0.05, undamped")


def numerics(N: Numbers):
    """Step 6.4, Appendix B: convergence of the tension with the quasi-static split
    (tests/test_response.py::test_split_convergence_with_damping, about 10 s)."""
    from beltloop import Loop, StartProfile, modal_basis, startup_response
    N.section("Appendix B (numerical methods): convergence of the modal tension")
    lp = Loop.from_positions(0.0, 0.02, 1.58, r_return=0.3, r_carry=0.9)
    prof = StartProfile("sine", 30.0, "velocity")
    tau = np.linspace(0, 80, 801)
    x = np.array([0.0, 0.5, 1.0, 2.0])
    b300, b20 = modal_basis(lp, 0.12, 300), modal_basis(lp, 0.12, 20)
    err, err_plain = 0.0, 0.0
    for zh in (0.0, 0.02, 0.1):
        ref = startup_response(b300, prof, zh, tau).tension(x)
        r20 = startup_response(b20, prof, zh, tau)
        scale = np.max(np.abs(ref))
        err = max(err, np.max(np.abs(r20.tension(x) - ref)) / scale)
        if zh == 0.02:
            err_plain = np.max(np.abs(r20.tension(x, "plain") - ref)) / scale
    N.add("SplitModes", 20, 0, "modes kept")
    N.add("SplitRefModes", 300, 0, "reference modes")
    N.add("SplitErr", err, "e1", "largest relative tension error, damping 0 to 0.1")
    N.add("PlainErr", err_plain, "e1", "the plain modal sum, same modes, zeta_hat = 0.02")


SECTIONS = (claims, modal, beta_regime, startup, crawl, validity, applications, validation,
            solution, numerics)


def build(recompute=False) -> Numbers:
    if recompute:
        refresh_validation()
    slow = slow_inputs(recompute)
    N = Numbers()
    for f in SECTIONS:
        f(N, slow) if f is applications else f(N)
    return N


def render(recompute=False) -> str:
    return build(recompute).tex()


def main(argv):
    text = render("--recompute" in argv)
    if "--check" in argv:
        ok = OUT.exists() and OUT.read_text() == text
        print("paper_numbers.tex is " + ("up to date" if ok else "OUT OF DATE: run maps/paper_numbers.py"))
        return 0 if ok else 1
    OUT.write_text(text)
    print(f"written: {OUT} ({text.count(chr(92) + 'newcommand')} macros)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
